// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUAmxxJZR9w9z8VYILpcewcXkQFtmGfX0',
    appId: '1:382877179056:android:e221d84dd9c02a6e932f75',
    messagingSenderId: '382877179056',
    projectId: 'kh-online-store-559cd',
    storageBucket: 'kh-online-store-559cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvLPPrimPiFwKB3mi81i2SoIOqt2KE-k',
    appId: '1:382877179056:ios:68a144d1c3795258932f75',
    messagingSenderId: '382877179056',
    projectId: 'kh-online-store-559cd',
    storageBucket: 'kh-online-store-559cd.firebasestorage.app',
    androidClientId: '382877179056-9jq39vjmbq63c7ej7l5haacttsg72q23.apps.googleusercontent.com',
    iosClientId: '382877179056-cho6jedcoh758kbc2mj154ephpu205mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.khOnlineStoreAdmin',
  );
}
