// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKSM2HDPda2LfVqUgShhG3vByi2flgPYM',
    appId: '1:382877179056:web:6503c4bfb3505f4c932f75',
    messagingSenderId: '382877179056',
    projectId: 'kh-online-store-559cd',
    authDomain: 'kh-online-store-559cd.firebaseapp.com',
    storageBucket: 'kh-online-store-559cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUAmxxJZR9w9z8VYILpcewcXkQFtmGfX0',
    appId: '1:382877179056:android:6ee871e583805d8b932f75',
    messagingSenderId: '382877179056',
    projectId: 'kh-online-store-559cd',
    storageBucket: 'kh-online-store-559cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvLPPrimPiFwKB3mi81i2SoIOqt2KE-k',
    appId: '1:382877179056:ios:6c7038aacedf84c0932f75',
    messagingSenderId: '382877179056',
    projectId: 'kh-online-store-559cd',
    storageBucket: 'kh-online-store-559cd.firebasestorage.app',
    androidClientId: '382877179056-9jq39vjmbq63c7ej7l5haacttsg72q23.apps.googleusercontent.com',
    iosClientId: '382877179056-v442dd7miheas1vfmkt1ovistc7dun1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.khOnlineStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvLPPrimPiFwKB3mi81i2SoIOqt2KE-k',
    appId: '1:382877179056:ios:6c7038aacedf84c0932f75',
    messagingSenderId: '382877179056',
    projectId: 'kh-online-store-559cd',
    storageBucket: 'kh-online-store-559cd.firebasestorage.app',
    androidClientId: '382877179056-9jq39vjmbq63c7ej7l5haacttsg72q23.apps.googleusercontent.com',
    iosClientId: '382877179056-v442dd7miheas1vfmkt1ovistc7dun1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.khOnlineStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKSM2HDPda2LfVqUgShhG3vByi2flgPYM',
    appId: '1:382877179056:web:545dc1bc441659f9932f75',
    messagingSenderId: '382877179056',
    projectId: 'kh-online-store-559cd',
    authDomain: 'kh-online-store-559cd.firebaseapp.com',
    storageBucket: 'kh-online-store-559cd.firebasestorage.app',
  );

}